name: ✨ Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['enhancement', 'needs-triage']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! ✨

        Please describe your idea clearly so we can understand the value it would bring.

  - type: textarea
    id: problem
    attributes:
      label: 🤔 Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Describe any alternative solutions or features you've considered

  - type: dropdown
    id: component
    attributes:
      label: 📦 Component
      description: Which package/component would this feature affect?
      options:
        - '@acme/kernel - Core DDD primitives'
        - '@acme/application - CQRS and use cases'
        - '@acme/errors - Error handling'
        - '@acme/config - Configuration'
        - '@acme/security - Authentication/Authorization'
        - '@acme/observability - Logging and metrics'
        - '@acme/messaging - Event handling'
        - '@acme/resilience - Fault tolerance'
        - '@acme/testing - Test utilities'
        - '@acme/web - HTTP adapters'
        - '@acme/contracts - API contracts'
        - '@acme/outbox - Transactional outbox'
        - '@acme/persistence - Repository pattern'
        - 'Multiple packages'
        - 'New package'
        - 'Documentation'
        - 'Build system'
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 📈 Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Important for adoption
        - Critical - Blocking major use cases
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: 🎯 Use Cases
      description: Describe specific use cases where this feature would be helpful
      placeholder: |
        1. As a developer, I want to...
        2. When building microservices, I need to...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: 🔧 API Design (Optional)
      description: If you have ideas about how the API should look, please share
      render: typescript

  - type: textarea
    id: additional
    attributes:
      label: 📚 Additional Context
      description: Add any other context, screenshots, or examples about the feature request

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: This feature aligns with the project's architecture principles
          required: true
        - label: I would be willing to contribute to implementing this feature
          required: false
